name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (apps/api)
        run: npm run --prefix apps/api test

      - name: Upload jest results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: apps/api/jest-junit.xml
