name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (apps/api)
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/app-kirimku-id:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/app-kirimku-id:latest

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Release created from tag ${{ github.ref_name }} by CI"
